assets can be missing from binder

diff --git a/bin/mockcloud-ensure-servers b/bin/mockcloud-ensure-servers
--- a/bin/mockcloud-ensure-servers
+++ b/bin/mockcloud-ensure-servers
@@ -73,10 +73,19 @@ if [[ $numServers -eq $numCurrServers ]]; then
     echo "Already have $numServers mock servers"
     exit 0
 elif [[ $numServers -gt $numCurrServers ]]; then
+    echo "Finding assets IP"
+    assets_ip=$(curl -sS http://sapi.$DCNAME.$DNSDOMAIN/services?name=sdc | json -H 0.metadata.assets-ip)
+    if [[ -z $assets_ip ]]; then
+        echo "FATAL: Unable to determine assets IP" >&2
+        exit 2
+    else
+        echo "Assets IP: $assets_ip"
+    fi
+
     echo "Ensuring we have latest agentsshar"
     while [[ ! -f /var/tmp/latest-agentsshar.sh && $agentsshar_retries -gt 0 ]]; do
         curl -o /var/tmp/latest-agentsshar.sh \
-            http://assets.$DCNAME.$DNSDOMAIN/extra/agents/latest \
+            http://$assets_ip/extra/agents/latest \
             || rm -f /var/tmp/latest-agentsshar.sh
         agentsshar_retries=$((agentsshar_retries - 1))
     done
